### ISSUE TITLE
Non-timeseries data & HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by jeppoo1** [pnuu/fmiopendata#12]
Testing **with the non-timeseries** data, the following code

```
start_time = "2020-10-15T11:00:00Z"
end_time = "2020-10-22T12:00:00Z"

obs = download_stored_query("fmi::observations::weather::multipointcoverage",
                            args=["bbox=24.88,60.14,25.01,60.19",  "bbox=24.88,60.14,25.01,60.19"
                                   "starttime=" + start_time,
                                  "endtime=" + end_time])
all_steps_list = list(obs.data.keys())
for i in range(0, len(all_steps_list)):
    print(all_steps_list[i])
```

throws me the following error:
**urllib.error.HTTPError: HTTP Error 400: Bad Request**

It seems that when the interval start_time --> end_time is more than 7 days, I am getting the HTTP Error 400. But with for example five days (`start_time = "2020-10-17T11:00:00Z"`
`end_time = "2020-10-22T12:00:00Z"`)
the code runs fine and returns me everything for those five days.

Is this how the library is supposed to work, **so that the non-timeseries download cannot return me more than 7 days of weather data in a single run of the script?**

------------------------------------------------------

Moreover, if I am using the script **with the timeseries data,** it only returns me **something like the last 12 hours of weather data with 72 data "steps"**, no matter what I set the start_time & end_time to. Example for trying to download a year worth of weather data:

```
start_time = "2017-10-22T05:44:16Z"
end_time = "2018-10-22T05:44:16Z"

obs = download_stored_query("fmi::observations::weather::multipointcoverage",
                            args=["bbox=24.87,60.14,25.01,60.19",  "bbox=24.88,60.14,25.01,60.19"
                                   "timeseries=True"])

print(len((obs.data["Helsinki Kaisaniemi"]["times"]))) 
# --> 72
for i in range(0, len((obs.data["Helsinki Kaisaniemi"]["times"]))):
    print(obs.data["Helsinki Kaisaniemi"]["times"][i])
# --> 2020-10-22 21:50:00
# 2020-10-22 22:00:00
# 2020-10-22 22:10:00
# 2020-10-22 22:20:00
# 2020-10-22 22:30:00
# 2020-10-22 22:40:00
# 2020-10-22 22:50:00
# 2020-10-22 23:00:00
# 2020-10-22 23:10:00
# 2020-10-22 23:20:00
# 2020-10-22 23:30:00
# 2020-10-22 23:40:00
# 2020-10-22 23:50:00
# 2020-10-23 00:00:00
# 2020-10-23 00:10:00
# 2020-10-23 00:20:00
# 2020-10-23 00:30:00
# 2020-10-23 00:40:00
# 2020-10-23 00:50:00
# 2020-10-23 01:00:00
# 2020-10-23 01:10:00
# 2020-10-23 01:20:00
# 2020-10-23 01:30:00
# 2020-10-23 01:40:00
# 2020-10-23 01:50:00
# 2020-10-23 02:00:00
# 2020-10-23 02:10:00
# 2020-10-23 02:20:00
# 2020-10-23 02:30:00
# 2020-10-23 02:40:00
# 2020-10-23 02:50:00
# 2020-10-23 03:00:00
# 2020-10-23 03:10:00
# 2020-10-23 03:20:00
# 2020-10-23 03:30:00
# 2020-10-23 03:40:00
# 2020-10-23 03:50:00
# 2020-10-23 04:00:00
# 2020-10-23 04:10:00
# 2020-10-23 04:20:00
# 2020-10-23 04:30:00
# 2020-10-23 04:40:00
# 2020-10-23 04:50:00
# 2020-10-23 05:00:00
# 2020-10-23 05:10:00
# 2020-10-23 05:20:00
# 2020-10-23 05:30:00
# 2020-10-23 05:40:00
# 2020-10-23 05:50:00
# 2020-10-23 06:00:00
# 2020-10-23 06:10:00
# 2020-10-23 06:20:00
# 2020-10-23 06:30:00
# 2020-10-23 06:40:00
# 2020-10-23 06:50:00
# 2020-10-23 07:00:00
# 2020-10-23 07:10:00
# 2020-10-23 07:20:00
# 2020-10-23 07:30:00
# 2020-10-23 07:40:00
# 2020-10-23 07:50:00
# 2020-10-23 08:00:00
# 2020-10-23 08:10:00
# 2020-10-23 08:20:00
# 2020-10-23 08:30:00
# 2020-10-23 08:40:00
# 2020-10-23 08:50:00
# 2020-10-23 09:00:00
# 2020-10-23 09:10:00
# 2020-10-23 09:20:00
# 2020-10-23 09:30:00
# 2020-10-23 09:40:00
```
(the latter script was run today 23.10.2020 at 12:49 (UTC/GMT +2 hours))

What could I do **in order to the timeseries script would actually return me the timespan that I have set with start_time & end_time?** @pnuu

**Comment by pnuu** [comment]
For the first part, the actual query to FMI servers is `http://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::observations::weather::multipointcoverage&bbox=24.88,60.14,25.01,60.19&starttime=2020-10-15T11:00:00Z&endttime=2020-10-22T12:00:00Z` which returns an error:
```xml
<ExceptionText>Too long time interval requested!</ExceptionText>
<ExceptionText>No more than 168.000000 hours allowed.</ExceptionText>
```
So the limitation is on the FMI side. I need to add handling for this kinds of errors so that the message will be passed to the users.

In the second call you haven't used the `start_time` and `end_time` in the query so they can't have any effect on the result. You can also remove the second `bbox` argument, once is enough :wink:

**Comment by jeppoo1** [comment]
Thank you very much @pnuu! 
You are totally correct, I forgot to delete the additional bbox I had in a comment, and I didn't know that I can add the start_time and end_time to the query. I was under the impression that it must be EITHER timeseries=True OR start_time & end_time (because of the documentation example only included timeseries: 
`It is also possible to collect the data to a structure more usable for timeseries analysis by adding "timeseries=True" to the arguments:`

`from fmiopendata.wfs import download_stored_query`

`obs = download_stored_query("fmi::observations::weather::multipointcoverage",`
`                           args=["bbox=25,60,25.5,60.5",`
`                                  "timeseries=True"])).`)

Did I understand correctly, that the situation is that if timeseries=False (only start_time and end_time added to the script), it is not possible to download more than 168 hours of historical weather data? And if timeseries=True (BOTH timeseries=True AND start_time & end_time passed to the script), then it is possible to download as much historical data as needed?

**Comment by pnuu** [comment]
The 168 hour limitation is on the FMI servers and doesn't have anything to do with `timeseries` keyword argument. It only affects the formatting and organisation of the data on `fmiopendata` library so that the data are easier to handle when collecting data for timeseries. The default (`timeseries=False)` returns the exact same data in a format that is more suitable for showing "live" weather data for multiple locations.

**Comment by pnuu** [comment]
Forgot to create a new release, but v0.3.3 is now available from PyPI.
