### ISSUE TITLE
dropsonde data ei tule?

### ISSUE THREAD

**Issue by paapu88** [pnuu/fmiopendata#17]
Hei,
Yritän ladata dropsonde dataa Jokiosista 11.11.2020
soundings data tulee hyvin mutta dropsonde dataa en saa mistään.

>>> import fmiopendata
>>> fmiopendata.__version__
'0.3.4'

Olisiko mahdollista saada toimiva esimerkki dropsonde datan hakemisesta?
Yritin esim. alla olevalla koodilla:

```
from datetime import datetime
from fmiopendata.wfs import download_stored_query

start_time = datetime(year=2020, month=1, day=11, hour=11, minute=24, second=36)
end_time = datetime(year=2020, month=12, day=13, hour=15, minute=43, second=57)
# Convert times to properly formatted strings
start_time = start_time.isoformat(timespec="seconds") + "Z"
# -> 2020-07-07T12:00:00Z
end_time = end_time.isoformat(timespec="seconds") + "Z"
snd = download_stored_query("fmi::observations::weather::dropsonde::multipointcoverage",
                            args=["starttime=" + start_time,
                                  "endtime=" + end_time]
                            )
```
ja tuloksena on 

```
/home/hu-mka/venvs/fmi/bin/python3 /home/hu-mka/git/fmi/fmi/demo_get_dropsonde_data.py
/home/hu-mka/venvs/fmi/lib/python3.8/site-packages/fmiopendata/utils.py:43: UserWarning: 

FMI servers responded with the following errors:

 - No handler for 'fmi::observations::weather::dropsondes::multipointcoverage' found!
 - URI: /wfs?endtime=2020-12-13T15%3A43%3A57Z&request=getFeature&service=WFS&starttime=2020-01-11T11%3A24%3A36Z&storedquery_id=fmi%3A%3Aobservations%3A%3Aweather%3A%3Adropsondes%3A%3Amultipointcoverage&version=2.0.0

  warnings.warn(exception_text)
No observations found

Process finished with exit code 0
```

**Comment by pnuu** [comment]
Jälkimmäisessä pätkässä näyttää olevan kirjoitusvirhe `storedquery_id`:ssä: `dropsondes` vs. oikea muoto `dropsonde`. Muutoin käyttämäsi haku on muotoiltu oikein.

Lisäksi tosin näkyy olevan ongelmaa Ilmatieteen laitoksen päässä, sillä oikealla `storedquery_id`:llä ja katsomalla [hakua](http://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi%3A%3Aobservations%3A%3Aweather%3A%3Adropsonde%3A%3Amultipointcoverage) suoraan selaimella, saan virheilmoituksen `Unknown parameter 'GeopHeight' in this query.` joka viittaa avoimen datan konfigurointivirheeseen.

Voisitko tehdä tuosta heille bugiraportin [tämän](https://www.ilmatieteenlaitos.fi/tukipyynto-avoimesta-datasta) sivun lopussa olevan lomakkeen kautta? Laita mukaan esimerkiksi tuo linkittämäni hakuosoite ja saatu virheilmoitus.

Suljen tämän tiketin, sillä ongelma ei (tällä kertaa :grin:) ole tässä kirjastossa :-)
