### ISSUE TITLE
The data fields are somehow mixed

### ISSUE THREAD

**Issue by plitkey** [pnuu/fmiopendata#2]
I got non-reasonable figures for snow depth in May and as I compare the data with the same place and time from "Lataa havainnot" service, I can see that the fields are somehow mixed.

>>> arglist
['fmisid=874863', 'starttime=2020-05-13T12:10:00', 'endtime=2020-05-13T12:40:00']
>>> obs = download_stored_query("fmi::observations::weather::multipointcoverage",args=arglist)
 >>> obs.data
{datetime.datetime(2020, 5, 13, 12, 10): {'Espoo Tapiola': {'Relative humidity': {'value': 45791.0, 'units': '%'}, 'Precipitation amount': {'value': 164.0, 'units': 'mm'}, 'Dew-point temperature': {'value': 0.0, 'units': 'degC'}, 'Air temperature': {'value': 4.1, 'units': 'degC'}, 'Present weather (auto)': {'value': 1.9, 'units': ''}, 'Gust speed': {'value': 0.0, 'units': 'm/s'}, 'Pressure (msl)': {'value': 1003.9, 'units': 'hPa'}, 'Cloud amount': {'value': 4.3, 'units': '1/8'}, 'Precipitation intensity': {'value': 7.0, 'units': 'mm/h'}, 'Wind speed': {'value': 1.4, 'units': 'm/s'}, 'Horizontal visibility': {'value': 81.0, 'units': 'm'}, 'Wind direction': {'value': nan, 'units': 'deg'}, 'Snow depth': {'value': 81.0, 'units': 'cm'}}}, datetime.datetime(2020, 5, 13, 12, 30): {'Espoo Tapiola': {'Relative humidity': {'value': 42893.0, 'units': '%'}, 'Precipitation amount': {'value': 171.0, 'units': 'mm'}, 'Dew-point temperature': {'value': 0.0, 'units': 'degC'}, 'Air temperature': {'value': 5.5, 'units': 'degC'}, 'Present weather (auto)': {'value': 3.1, 'units': ''}, 'Gust speed': {'value': 0.0, 'units': 'm/s'}, 'Pressure (msl)': {'value': 1003.8, 'units': 'hPa'}, 'Cloud amount': {'value': 4.2, 'units': '1/8'}, 'Precipitation intensity': {'value': 7.0, 'units': 'mm/h'}, 'Wind speed': {'value': 1.1, 'units': 'm/s'}, 'Horizontal visibility': {'value': 81.0, 'units': 'm'}, 'Wind direction': {'value': nan, 'units': 'deg'}, 'Snow depth': {'value': 80.0, 'units': 'cm'}}}, datetime.datetime(2020, 5, 13, 12, 20): {'Espoo Tapiola': {'Relative humidity': {'value': 40083.0, 'units': '%'}, 'Precipitation amount': {'value': 182.0, 'units': 'mm'}, 'Dew-point temperature': {'value': 0.0, 'units': 'degC'}, 'Air temperature': {'value': 4.5, 'units': 'degC'}, 'Present weather (auto)': {'value': 2.5, 'units': ''}, 'Gust speed': {'value': 0.0, 'units': 'm/s'}, 'Pressure (msl)': {'value': 1003.9, 'units': 'hPa'}, 'Cloud amount': {'value': 4.3, 'units': '1/8'}, 'Precipitation intensity': {'value': 7.0, 'units': 'mm/h'}, 'Wind speed': {'value': 1.3, 'units': 'm/s'}, 'Horizontal visibility': {'value': 81.0, 'units': 'm'}, 'Wind direction': {'value': nan, 'units': 'deg'}, 'Snow depth': {'value': 81.0, 'units': 'cm'}}}, datetime.datetime(2020, 5, 13, 12, 40): {'Espoo Tapiola': {'Relative humidity': {'value': 40529.0, 'units': '%'}, 'Precipitation amount': {'value': 149.0, 'units': 'mm'}, 'Dew-point temperature': {'value': 0.0, 'units': 'degC'}, 'Air temperature': {'value': 4.7, 'units': 'degC'}, 'Present weather (auto)': {'value': 2.8, 'units': ''}, 'Gust speed': {'value': 0.0, 'units': 'm/s'}, 'Pressure (msl)': {'value': 1003.8, 'units': 'hPa'}, 'Cloud amount': {'value': 5.0, 'units': '1/8'}, 'Precipitation intensity': {'value': 7.0, 'units': 'mm/h'}, 'Wind speed': {'value': 1.1, 'units': 'm/s'}, 'Horizontal visibility': {'value': 23.0, 'units': 'm'}, 'Wind direction': {'value': nan, 'units': 'deg'}, 'Snow depth': {'value': 76.0, 'units': 'cm'}}}}

The keys have been mixed. The values are the same as from https://cdn.fmi.fi/fmiodata-convert-api/

Thanks for help!

**Comment by plitkey** [comment]
Does this have something to do with dicts being ordered after Python 3.7? I'm using Python 3.5.2

**Comment by pnuu** [comment]
Oh, good point! i was wondering why I'm not seeing the same problem.

I see two possible solutions:

1. use `OrderedDicts` for Python < 3.7
2. require Python 3.7 or newer.

I think I'll go with the first option to give the users more freedom.

**Comment by pnuu** [comment]
Actually it's 3.6 that already has the ordered dictionaries. But I'll add the workaround anyways for now.

**Comment by pnuu** [comment]
Version 0.2.3 should fix this for older Python versions. New version is available from PyPi with `pip install -U fmiopendata`.

**Comment by pnuu** [comment]
I noticed that for Python versions earlier than 3.6 the `.isoformat()` method of `datetime` objects doesn't support the `timespec` keyword argument that is used in the unit tests. I'll make Python 3.6+ a hard requirement in the next feature update (version 0.3.x), and will revert this `OrderedDict` workaround at the same time.
