### ISSUE TITLE
grid data fails due to "AttributeError: module 'eccodes' has no attribute 'GribFile'" 

### ISSUE THREAD

**Issue by paapu88** [pnuu/fmiopendata#35]
```
 File "/home/hu-mka/miniconda3/envs/fmisaa/lib/python3.9/site-packages/fmiopendata/grid.py", line 80, in _parse_grib
    with eccodes.GribFile(self._fname) as grib:
AttributeError: module 'eccodes' has no attribute 'GribFile'
```
I have installed eccodes by 
```
conda create -n fmisaa python=3.9
conda activate fmisaa
pip install fmiopendata
conda install -c conda-forge eccodes
pip install eccodes
conda install -c conda-forge cfgrib
```
Some sort of self check passes (from ` https://github.com/ecmwf/cfgrib#binary-dependencies` )
```
python -m cfgrib selfcheck
Found: ecCodes v2.27.0.
Your system is ready.

```
The code that produced the error (below) tries to read 4d gridded data. I guess there is no netcdf option for the data?
A description how to setup a working environment for this task would be appreciated.
Terveisin Markus
```
from fmiopendata.wfs import download_stored_query
import datetime

starttime = datetime.datetime.utcnow() + datetime.timedelta(hours=10)
endtime = starttime + datetime.timedelta(hours=50)
starttime = starttime.strftime("%Y-%m-%dT%H:%M:%SZ")
endtime = endtime.strftime("%Y-%m-%dT%H:%M:%SZ")

print(f"starttime {starttime}")
print(f"endtime {endtime}")

data = download_stored_query(
    "fmi::forecast::harmonie::surface::grid",
    args=[
        f"starttime={starttime}",
        f"endtime={endtime}",
        "bbox=25,60,26,61",
    ],
)

latest = max(data.data.keys())
data = data.data[latest]
print(f"downloading data for {latest}")
data.parse(delete=True)

```

**Comment by pnuu** [comment]
Thanks for the report! It seems that `eccodes` has changed something since I last had time to test this library. I'll see if I can figure out how to fix it.

**Comment by pnuu** [comment]
The small change in #36 seemed to fix this for me. I'll merge it to `main` when the tests have passed and create a new release on PyPI after that.

**Comment by pnuu** [comment]
Version 0.4.0 is now available on PyPI.

I also updated the installation instructions in the README file:

```bash
conda install eccodes -c conda-forge
pip install eccodes
```

should now install the extra needed packages.

I'll close this issue, let me know if that didn't help!

**Comment by paapu88** [comment]
Thanks, I did not use this but took data instead (in netcdf format) from Norway
https://github.com/metno/NWPdocs/wiki/Examples
